default:
  run1:
    files:
      bands: /shares/CIBIO-Storage/BCG/scratch/mimesis/scna/config/ucsc_cytobands_GRCh38.tsv
      bed: /shares/CIBIO-Storage/BCGLAB/mimesis/panel_design/panel/mimesis_panel/outs_hyperdesign/SelectionResult/mim_v4_capture_targets.bed
      controls: /home/riccardo/Documents/github/test_scna/data/controls.txt
      samples: /home/riccardo/Documents/github/test_scna/data/plasma.txt
    paths:
      ref: ./data/reference
      out: /home/riccardo/Documents/github/test_scna/data/out_test
    ref:
      overwrite: yes
      minaf: 0.2
      maxaf: 0.8
      mincov: 10.0
      centeraf: yes
      cov.bin: 0.1
      maskratio: 0.5
    sample:
      minaf: 0.1
      maxaf: 0.9
      mincov: 10.0
      minsnps: 10.0
      zthr: 1.96
      evidencethr: 0.5
    system:
      njobs: 1