default:
  run1:
    files:
      bands: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/config/ucsc_cytobands_GRCh38.tsv"
      bed: "/shares/CIBIO-Storage/BCGLAB/mimesis/panel_design/panel/mimesis_panel/outs_hyperdesign/SelectionResult/mim_v4_capture_targets.bed"
      controls: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/config/controls.txt"
      samples: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/config/cohort_0.txt"

    paths:
      ref: "./data/reference"
      out: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/analysis/cohort_0/run_e08z258"

    ref:
      overwrite: TRUE
      minaf: 0.2
      maxaf: 0.8
      mincov: 10
      centeraf: TRUE
      cov.bin: 0.1
      maskratio: 0.5
      
    sample:
      minaf: 0.1
      maxaf: 0.9
      mincov: 10
      minsnps: 10
      zthr: 2.58
      evidencethr: 0.8
      
    system:
      njobs: 36
      
  run2:
    files:
      bands: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/config/ucsc_cytobands_GRCh38.tsv"
      bed: "/shares/CIBIO-Storage/BCGLAB/mimesis/panel_design/panel/mimesis_panel/outs_hyperdesign/SelectionResult/mim_v4_capture_targets.bed"
      controls: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/config/controls.txt"
      samples: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/config/cohort_0.txt"

    paths:
      ref: "./data/reference"
      out: "/shares/CIBIO-Storage/BCG/scratch/mimesis/scna/analysis/cohort_0/run_e1z258"

    ref:
      overwrite: TRUE
      minaf: 0.2
      maxaf: 0.8
      mincov: 10
      centeraf: TRUE
      cov.bin: 0.1
      maskratio: 0.5
      
    sample:
      minaf: 0.1
      maxaf: 0.9
      mincov: 10
      minsnps: 10
      zthr: 2.58
      evidencethr: 1
      
    system:
      njobs: 36    
